# Generated by Django 3.1.7 on 2025-05-16 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id_g', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id_i', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id_o', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('id_g', models.ForeignKey(db_column='id_g', on_delete=django.db.models.deletion.CASCADE, to='core.groups')),
            ],
            options={
                'unique_together': {('id_g', 'name')},
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='id_i',
            field=models.ForeignKey(db_column='id_i', on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
        migrations.CreateModel(
            name='FactsStandards',
            fields=[
                ('id_s', models.AutoField(primary_key=True, serialize=False)),
                ('fact', models.TextField()),
                ('id_o', models.ForeignKey(db_column='id_o', on_delete=django.db.models.deletion.CASCADE, to='core.object')),
            ],
        ),
        migrations.CreateModel(
            name='FactsDetermination',
            fields=[
                ('id_d', models.AutoField(primary_key=True, serialize=False)),
                ('fact_name', models.CharField(max_length=255)),
                ('id_o', models.ForeignKey(db_column='id_o', on_delete=django.db.models.deletion.CASCADE, to='core.object')),
            ],
        ),
        migrations.CreateModel(
            name='FactsDefects',
            fields=[
                ('id_def', models.AutoField(primary_key=True, serialize=False)),
                ('fact', models.TextField()),
                ('criticality', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('id_o', models.ForeignKey(db_column='id_o', on_delete=django.db.models.deletion.CASCADE, to='core.object')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groups',
            unique_together={('id_i', 'name')},
        ),
    ]
