# Generated by Django 3.1.7 on 2025-05-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id_g', models.AutoField(primary_key=True, serialize=False)),
                ('название', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id_i', models.AutoField(primary_key=True, serialize=False)),
                ('название', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id_o', models.AutoField(primary_key=True, serialize=False)),
                ('название', models.CharField(max_length=255)),
                ('id_g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='core.groups')),
            ],
            options={
                'unique_together': {('id_g', 'название')},
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id_def', models.AutoField(primary_key=True, serialize=False)),
                ('испытание', models.TextField()),
                ('метрика', models.FloatField()),
                ('рекомендация', models.TextField()),
                ('id_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.object')),
            ],
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id_s', models.AutoField(primary_key=True, serialize=False)),
                ('стандарт', models.TextField()),
                ('требование', models.TextField()),
                ('id_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='core.object')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='id_i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.inventory'),
        ),
        migrations.AlterUniqueTogether(
            name='groups',
            unique_together={('id_i', 'название')},
        ),
    ]
