# Generated by Django 3.1.7 on 2025-05-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='id_i',
            field=models.ForeignKey(db_column='id_i_id', on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
        migrations.AlterField(
            model_name='object',
            name='id_g',
            field=models.ForeignKey(db_column='id_g_id', on_delete=django.db.models.deletion.CASCADE, to='core.groups'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='id_o',
            field=models.ForeignKey(db_column='id_o_id', on_delete=django.db.models.deletion.CASCADE, to='core.object'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='id_o',
            field=models.ForeignKey(db_column='id_o_id', on_delete=django.db.models.deletion.CASCADE, to='core.object'),
        ),
    ]
